apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calendar-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/sg6/argo-lab-calendar-app.git
    targetRevision: main
    path: devops/k8s_manifests/calendar-app
  destination:
    server: https://kubernetes.default.svc
    namespace: calendar-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
