apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 40.2.0
    helm:
      releaseName: traefik
      values: |
        ingressClass:
          enabled: false
        providers:
          kubernetesCRD:
            enabled: false
          kubernetesIngress:
            enabled: false
          kubernetesGateway:
            enabled: true
        gateway:
          enabled: false
        service:
          spec:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
