apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-backend
  namespace: calendar-app
  labels:
    app.kubernetes.io/name: calendar-backend
    app.kubernetes.io/part-of: calendar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: calendar-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calendar-backend
        app.kubernetes.io/part-of: calendar-app
    spec:
      initContainers:
        - name: prisma-db-push
          image: ghcr.io/sg6/argo-lab-calendar-app-backend:0.0.2
          command:
            - npx
            - prisma
            - db
            - push
          envFrom:
            - secretRef:
                name: calendar-backend-secret
      containers:
        - name: backend
          image: ghcr.io/sg6/argo-lab-calendar-app-backend:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: calendar-backend-config
            - secretRef:
                name: calendar-backend-secret
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
