apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database-secret.yaml
  - database-cluster.yaml
  - backend-secret.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - gateway.yaml
  - http-route.yaml
